spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///movie?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource